# Dependabot will run on day 27 of each month at 01:26 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "26 1 27 * *"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "26 1 27 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/src-widgets"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "26 1 27 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
